### PR TITLE
Added PSD and ISD2 Device

### PR DESCRIPTION
**Pull request by acidburn78**
Added the PSD (Plugable Dimmer) and ISD2 (InWall-Dimmer)
I only had the PSD so hopefully also the ISD2 works like the PSD-Device

### CODE REVIEW

**Comment by planbnet** [comment]
The way you implemented this looks good. But I don't think this will work in this state: Please fix the errors that the ruff check states (missing import)

Additionally, this should probably also react to changes sent from the device to adjust the state in hass.

**Comment by acidburn78** [comment]
if i look here [there](https://service.startsmarthome.de/de/smarthome-geraete-uebersicht) is no PSDO only a PSSO (not dimmable) the PSSO is implemented

**Comment by planbnet** [comment]
Thank you. Lets see if this works for people who have the dimmer. As I cannot test it, I'll wait a bit before creating a release.

**Comment by ThMFlive** [comment]
Both dimmer devices works very fine and without problems. Very good job.

**Comment by Gerrett84** [comment]
Just added my ISD2 Dimmer. When I control from Hassio it works without any problems. As soon as I switch the ISD2 manually, via openhab or the Livisi app, the status in Hassio is not updated.

**Comment by planbnet** [comment]
Yeah, I expected that... The code to react to state changes from the dimmer was not implemented by @acidburn78  unfortunately.

**Pull request merged**
