### PR TITLE
Add reboot button

### PR DESCRIPTION
**Pull request by DanielHabenicht**
just as a heads-up (after the other PR) I would like to add the reboot button so one can also restart the SHC. 

Testing with SHC2 is highly appreciated.

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
There is a bug unrelated to this feature but only highlighted by it: 
After a restart, all entities stay "Unavailable". Only after a reload of the Add-In they are updated. 
Is there no retry mechanism for restoring the state once the central unit is available again?

**Comment by DanielHabenicht** [comment]
Updated and tested again on the SHC1.

**Comment by DanielHabenicht** [comment]
I found out how to release beta release for HACS. Simply publish a prerelease (e.g. from the develop branch) and it will show up automatically. 
Could you do that? Thanks!

**Comment by planbnet** [comment]
I already did that for https://github.com/planbnet/livisi_unofficial/releases/tag/1.10.0
That one seems to work fine, so I'll set it to released now and create a new one for the release button

**Pull request merged**
