### PR TITLE
Add BT Power Plug and dedictated Sensors for VRCC Devices

### PR DESCRIPTION
**Pull request by acidburn78**
I added the Medion Power Plug with a Powersensor

### CODE REVIEW

**Comment by acidburn78** [comment]
Added dedicated Temperature an Humidity Sensors

**Comment by planbnet** [comment]
Ok, sorry, I got a bit too motivated and attacked the TODO point with removing the unnecessary aiolivisi lib abstractions. There's a bit of refactoring to do now. 

And after thinking a bit more about it, I would really like to add the humidity and temperature sensors for the thermostat devices and not for the VRCC virtual room climate devices. This makes sense because they currently only have the battery indicator (which is not working yet). For most people (with just one thermostat per room) it doesn't matter where the sensors are located, and the room avg temperature can still be retrieved from the attributes in the climate devices.

**Comment by acidburn78** [comment]
I can add the sensors to both vrcc and rst so everyone can decide witch sensors he would use. From the attributes you have to work with templates

**Comment by planbnet** [comment]
I rewrote the sensor implementation to be more generic and integrated support for temp and humidity for VRCC and RST devices. Just to let you know: your implementation broke device naming for VRCCs, because devices were created without "use room name as device name".
Additionally, entity names should not contain the device name. That is handled by home assistant.

Please create a new PR for the "Medion Power Plug with a Powersensor" or adjust this one if you still like to integrate that.

**Pull request closed without merging**
