### PR TITLE
fix sensors keep unavailable state

### PR DESCRIPTION
**Pull request by DanielHabenicht**
Because the entity `_attr_available` is set to false when the plugin is loaded subsequent updates (when a window is opened or closed) are not visible as the property is not set back to `true`. 
This resolves the issue by updating it too. 

This is a fix for the problem I mentioned in #92

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
I think this also applies to the other Entities I added in the second commit.
At least for HVAC entities, I already experienced it once.

**Review by planbnet — APPROVED** [review]
LGTM

**Comment by DanielHabenicht** [comment]
Would it be possible to setup a beta release for the `develop` Branch?
I already looked it up but couldn't find the documentation on HACS. 

This way it would be easier to test before a proper release.

**Comment by planbnet** [comment]
I tried to publish a "pre-release" on guthub: https://github.com/planbnet/livisi_unofficial/releases/tag/1.10.0
But it looks like HCS simply pulls this as the latest release...

**Comment by olli711** [comment]
Hi,

Better not install? I am eagerly waiting for the binary sensors😅

**Comment by planbnet** [comment]
I have the development version running for a few days now without problems. I'd say give it a try.

**Comment by olli711** [comment]
Perfect. I will try it. I'm curious to see how it goes

**Pull request merged**
